-- SET GLOBAL time_zone = '-6:00';

DROP DATABASE IF EXISTS games;
CREATE DATABASE games;
USE games;

CREATE OR REPLACE TABLE game (
id INT UNSIGNED AUTO_INCREMENT,
numOfPlayers INT UNSIGNED NOT NULL,
PRIMARY KEY (id)
);

CREATE OR REPLACE TABLE move (
game INT UNSIGNED NOT NULL,
moveNumber INT UNSIGNED NOT NULL,
oldX INT UNSIGNED NOT NULL,
oldY INT UNSIGNED NOT NULL,
newX INT UNSIGNED NOT NULL,
newY INT UNSIGNED NOT NULL,
FOREIGN KEY (game) REFERENCES  game(id),
PRIMARY KEY (game, moveNumber)
);
